export const ADD_PROJECTTYPE = "ADD_PROJECTTYPE";
export const GET_PROJECTTYPE = "GET_PROJECTTYPE";
export const DELETE_PROJECTTYPE = "DELETE_PROJECTTYPE";
export const EDIT_PROJECTTYPE = "EDIT_PROJECTTYPE";
