export const GET_DOCUMENTSCHEDULE = "GET_DOCUMENTSCHEDULE";
export const DELETE_DOCUMENTSCHEDULE = "DELETE_DOCUMENTSCHEDULE";
export const GET_DOCUMENTSCHEDULEONE = "GET_DOCUMENTSCHEDULEONE";
export const DELETE_DOCUMENTSCHEDULEONE = "DELETE_DOCUMENTSCHEDULEONE";
export const GET_DOCUMENT_SCHEDULE_USER = "GET_DOCUMENT_SCHEDULE_USER";
