export const GET_DAILYREPORT = "GET_DAILYREPORT";
export const GET_LISTREPORT = "GET_LISTREPORT";
export const GET_VIEWDAILYREPORT = "GET_VIEWDAILYREPORT";
export const GET_DAILYREPORT_ASSIGN = "GET_DAILYREPORT_ASSIGN";
export const GET_DAILYREPORT_DIVISION = "GET_DAILYREPORT_DIVISION";
