export const GET_PROJECTSCHEDULE = "GET_PROJECTSCHEDULE";
export const DELETE_PROJECTSCHEDULE = "DELETE_PROJECTSCHEDULE";
export const GET_PROJECTSCHEDULEONE = "GET_PROJECTSCHEDULEONE";
export const DELETE_PROJECTSCHEDULEONE = "DELETE_PROJECTSCHEDULEONE";
export const GET_PROJECT_SCHEDULE_USER ="GET_PROJECT_SCHEDULE_USER";