export const GET_PROJECT = "GET_PROJECT";
export const GET_PROJECT_ONE = "GET_PROJECT_ONE";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const POST_PROJECT = "POST_PROJECT";