export const ADD_GENERATION = "ADD_PROJECTTYPE";
export const GET_GENERATION = "GET_GENERATION";
export const DELETE_GENERATION = "DELETE_GENERATION";
export const EDIT_GENERATION = "EDIT_GENERATION";